//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1008
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.MsgResource.ORIGINAL {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainteLogMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainteLogMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.MsgResource.ORIGINAL.MainteLogMsg", typeof(MainteLogMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1側旋回 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0201 {
            get {
                return ResourceManager.GetString("MLOG_0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1側前後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0202 {
            get {
                return ResourceManager.GetString("MLOG_0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1側防水挿入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0203 {
            get {
                return ResourceManager.GetString("MLOG_0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1側圧着 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0204 {
            get {
                return ResourceManager.GetString("MLOG_0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット・ストリップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0205 {
            get {
                return ResourceManager.GetString("MLOG_0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2側搬送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0206 {
            get {
                return ResourceManager.GetString("MLOG_0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2側前後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0207 {
            get {
                return ResourceManager.GetString("MLOG_0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2側防水挿入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0208 {
            get {
                return ResourceManager.GetString("MLOG_0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2側圧着 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0209 {
            get {
                return ResourceManager.GetString("MLOG_0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_020A {
            get {
                return ResourceManager.GetString("MLOG_020A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_0999 {
            get {
                return ResourceManager.GetString("MLOG_0999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: ベースマシン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1001 {
            get {
                return ResourceManager.GetString("MLOG_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: 圧着 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1002 {
            get {
                return ResourceManager.GetString("MLOG_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: 排出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1003 {
            get {
                return ResourceManager.GetString("MLOG_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: ワイヤーフィード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1004 {
            get {
                return ResourceManager.GetString("MLOG_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: 防水シール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1005 {
            get {
                return ResourceManager.GetString("MLOG_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: No 1 前後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1006 {
            get {
                return ResourceManager.GetString("MLOG_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: No 2 前後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1007 {
            get {
                return ResourceManager.GetString("MLOG_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: ストリップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1008 {
            get {
                return ResourceManager.GetString("MLOG_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: 旋回 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1009 {
            get {
                return ResourceManager.GetString("MLOG_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値: 搬送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_100A {
            get {
                return ResourceManager.GetString("MLOG_100A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイミング: 1側 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1101 {
            get {
                return ResourceManager.GetString("MLOG_1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイミング: 2側 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1102 {
            get {
                return ResourceManager.GetString("MLOG_1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイミング: 排出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1103 {
            get {
                return ResourceManager.GetString("MLOG_1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイミング: 防水1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1104 {
            get {
                return ResourceManager.GetString("MLOG_1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイミング: 防水2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLOG_1105 {
            get {
                return ResourceManager.GetString("MLOG_1105", resourceCulture);
            }
        }
    }
}
