//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.MsgResource.ORIGINAL {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusDspMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusDspMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.MsgResource.ORIGINAL.StatusDspMsg", typeof(StatusDspMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ストリップミス1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0000 {
            get {
                return ResourceManager.GetString("STA_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップミス2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0001 {
            get {
                return ResourceManager.GetString("STA_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着ミス1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0002 {
            get {
                return ResourceManager.GetString("STA_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着ミス2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0003 {
            get {
                return ResourceManager.GetString("STA_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端子有無1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0004 {
            get {
                return ResourceManager.GetString("STA_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端子有無2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0005 {
            get {
                return ResourceManager.GetString("STA_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端子過負荷1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0006 {
            get {
                return ResourceManager.GetString("STA_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端子過負荷2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0007 {
            get {
                return ResourceManager.GetString("STA_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水栓挿入1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0008 {
            get {
                return ResourceManager.GetString("STA_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水栓挿入2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0009 {
            get {
                return ResourceManager.GetString("STA_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水栓有無1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_000A {
            get {
                return ResourceManager.GetString("STA_000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水栓有無2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_000B {
            get {
                return ResourceManager.GetString("STA_000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エアフィード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_001E {
            get {
                return ResourceManager.GetString("STA_001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックフィード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_001F {
            get {
                return ResourceManager.GetString("STA_001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイド端子1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0020 {
            get {
                return ResourceManager.GetString("STA_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイド端子2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0021 {
            get {
                return ResourceManager.GetString("STA_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンド端子1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0022 {
            get {
                return ResourceManager.GetString("STA_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンド端子2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0023 {
            get {
                return ResourceManager.GetString("STA_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着退避1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0024 {
            get {
                return ResourceManager.GetString("STA_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着退避2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0025 {
            get {
                return ResourceManager.GetString("STA_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F線ガイド1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0026 {
            get {
                return ResourceManager.GetString("STA_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F線ガイド2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0027 {
            get {
                return ResourceManager.GetString("STA_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバトップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0028 {
            get {
                return ResourceManager.GetString("STA_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後退持替 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_0029 {
            get {
                return ResourceManager.GetString("STA_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ1A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_002B {
            get {
                return ResourceManager.GetString("STA_002B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ2A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_002C {
            get {
                return ResourceManager.GetString("STA_002C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ1B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_002D {
            get {
                return ResourceManager.GetString("STA_002D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ2B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STA_002E {
            get {
                return ResourceManager.GetString("STA_002E", resourceCulture);
            }
        }
    }
}
