//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.MsgResource.ORIGINAL {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemScreenMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemScreenMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.MsgResource.ORIGINAL.SystemScreenMsg", typeof(SystemScreenMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0001 {
            get {
                return ResourceManager.GetString("SYS_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0002 {
            get {
                return ResourceManager.GetString("SYS_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0003 {
            get {
                return ResourceManager.GetString("SYS_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリケーションの多重起動は行えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0004 {
            get {
                return ResourceManager.GetString("SYS_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリケーションをリモートセッションから起動することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0005 {
            get {
                return ResourceManager.GetString("SYS_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ割当データの機種名が前回起動時と異なります。
        ///このまま起動を続けてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0006 {
            get {
                return ResourceManager.GetString("SYS_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動機のデータが初期化されていません。初期化してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0007 {
            get {
                return ResourceManager.GetString("SYS_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対応するワークIDが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0008 {
            get {
                return ResourceManager.GetString("SYS_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドレスの範囲が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0009 {
            get {
                return ResourceManager.GetString("SYS_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの長さが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000A {
            get {
                return ResourceManager.GetString("SYS_000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が適正範囲ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000B {
            get {
                return ResourceManager.GetString("SYS_000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータをデフォルト値で補いました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000C {
            get {
                return ResourceManager.GetString("SYS_000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定ファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000D {
            get {
                return ResourceManager.GetString("SYS_000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ割当データファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000E {
            get {
                return ResourceManager.GetString("SYS_000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000F {
            get {
                return ResourceManager.GetString("SYS_000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値ファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0010 {
            get {
                return ResourceManager.GetString("SYS_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0011 {
            get {
                return ResourceManager.GetString("SYS_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードとパスワード（確認）の値が異なります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0012 {
            get {
                return ResourceManager.GetString("SYS_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定を行いました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0013 {
            get {
                return ResourceManager.GetString("SYS_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータ値範囲外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0014 {
            get {
                return ResourceManager.GetString("SYS_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0015 {
            get {
                return ResourceManager.GetString("SYS_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上の値を入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0016 {
            get {
                return ResourceManager.GetString("SYS_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対応するWORKIDが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0017 {
            get {
                return ResourceManager.GetString("SYS_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に値が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0018 {
            get {
                return ResourceManager.GetString("SYS_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のフォーマットが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0019 {
            get {
                return ResourceManager.GetString("SYS_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は、{1}から{2}の範囲で入力を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001A {
            get {
                return ResourceManager.GetString("SYS_001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は、{1}以上の値かつ、{2}未満の値を入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001B {
            get {
                return ResourceManager.GetString("SYS_001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動機との同期が行われていないため、操作を行うことができません。
        ///自動機に接続を行ってから操作を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001C {
            get {
                return ResourceManager.GetString("SYS_001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONLINE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001D {
            get {
                return ResourceManager.GetString("SYS_001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFFLINE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001E {
            get {
                return ResourceManager.GetString("SYS_001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   のバージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001F {
            get {
                return ResourceManager.GetString("SYS_001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0020 {
            get {
                return ResourceManager.GetString("SYS_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   学習データをデフォルト値で補いました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0021 {
            get {
                return ResourceManager.GetString("SYS_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電線名、又は電線サイズが入力されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0022 {
            get {
                return ResourceManager.GetString("SYS_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CFM-MX (N) 20 に接続出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0023 {
            get {
                return ResourceManager.GetString("SYS_0023", resourceCulture);
            }
        }
    }
}
