//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.MsgResource.ORIGINAL {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimingDataMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimingDataMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.MsgResource.ORIGINAL.TimingDataMsg", typeof(TimingDataMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   先端クランプ閉→搬送クランプ閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0101 {
            get {
                return ResourceManager.GetString("TIMM_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット閉(完了)→前後ストリップ位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0102 {
            get {
                return ResourceManager.GetString("TIMM_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後ストリップ位置→旋回ストリップST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0103 {
            get {
                return ResourceManager.GetString("TIMM_0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ安定時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0104 {
            get {
                return ResourceManager.GetString("TIMM_0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ閉(完了)→前後ストリップ後退位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0105 {
            get {
                return ResourceManager.GetString("TIMM_0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.圧着後退位置→旋回.原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0106 {
            get {
                return ResourceManager.GetString("TIMM_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旋回.原位置→前後.原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0107 {
            get {
                return ResourceManager.GetString("TIMM_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.原位置→フィード開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0108 {
            get {
                return ResourceManager.GetString("TIMM_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード終了→電線ガイド閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0109 {
            get {
                return ResourceManager.GetString("TIMM_0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックフィード: 前後.原位置→バックフィード開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_010A {
            get {
                return ResourceManager.GetString("TIMM_010A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックフィード: バックフィード終了→フィード開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_010B {
            get {
                return ResourceManager.GetString("TIMM_010B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旋回.圧着位置→バキュームOFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_010C {
            get {
                return ResourceManager.GetString("TIMM_010C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハーフ: 前後.ハーフ後退位置→旋回(前後).原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_010D {
            get {
                return ResourceManager.GetString("TIMM_010D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハーフ: 旋回(前後).原位置→フィード開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_010E {
            get {
                return ResourceManager.GetString("TIMM_010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1沈み上 → キャリアカットOFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_010F {
            get {
                return ResourceManager.GetString("TIMM_010F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリアカットON → キャリアカットOFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0110 {
            get {
                return ResourceManager.GetString("TIMM_0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着退避: No1沈み上→旋回.圧着退避ST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0111 {
            get {
                return ResourceManager.GetString("TIMM_0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着退避: 旋回.圧着退避ST→前後.圧着検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0112 {
            get {
                return ResourceManager.GetString("TIMM_0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定終了後圧着:圧着開始待ち時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0113 {
            get {
                return ResourceManager.GetString("TIMM_0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送クランプ閉→カット閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0201 {
            get {
                return ResourceManager.GetString("TIMM_0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット閉(完了)→前後.ストリップ位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0202 {
            get {
                return ResourceManager.GetString("TIMM_0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.ストリップ位置→搬送.ストリップST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0203 {
            get {
                return ResourceManager.GetString("TIMM_0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ安定時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0204 {
            get {
                return ResourceManager.GetString("TIMM_0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ閉(完了)→前後.ストリップ後退位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0205 {
            get {
                return ResourceManager.GetString("TIMM_0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.ストリップ後退位置→搬送.圧着ST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0206 {
            get {
                return ResourceManager.GetString("TIMM_0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.持替ST→排出クランプ閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0207 {
            get {
                return ResourceManager.GetString("TIMM_0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送クランプ開→搬送.原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0208 {
            get {
                return ResourceManager.GetString("TIMM_0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.原位置→前後.原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0209 {
            get {
                return ResourceManager.GetString("TIMM_0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.圧着ST→バキュームOFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_020A {
            get {
                return ResourceManager.GetString("TIMM_020A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハーフ: 前後.ハーフ後退位置→搬送(前後).持替位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_020B {
            get {
                return ResourceManager.GetString("TIMM_020B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハーフ: 搬送(前後).持替位置→排出クランプ閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_020C {
            get {
                return ResourceManager.GetString("TIMM_020C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2沈み上→キャリアカットON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_020D {
            get {
                return ResourceManager.GetString("TIMM_020D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリアカットON→キャリアカットOFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_020E {
            get {
                return ResourceManager.GetString("TIMM_020E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバートップ:No2沈み上→前後.先端持替位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_020F {
            get {
                return ResourceManager.GetString("TIMM_020F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.圧着ST→前後.先端持替位置(切替プラス) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0210 {
            get {
                return ResourceManager.GetString("TIMM_0210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.圧着ST→圧着開始(切替プラス) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0211 {
            get {
                return ResourceManager.GetString("TIMM_0211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.圧着ST→排出クランプ閉(切替プラス) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0212 {
            get {
                return ResourceManager.GetString("TIMM_0212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着退避: No2沈み上→搬送.圧着退避ST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0213 {
            get {
                return ResourceManager.GetString("TIMM_0213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定終了後圧着: 圧着開始待ち時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0214 {
            get {
                return ResourceManager.GetString("TIMM_0214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定終了後圧着: 排出クランプ閉待ち時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0215 {
            get {
                return ResourceManager.GetString("TIMM_0215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.ストリップ検出準備ST→前後.ストリップ検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0216 {
            get {
                return ResourceManager.GetString("TIMM_0216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.ストリップ検出位置→搬送.ストリップ検出ST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0217 {
            get {
                return ResourceManager.GetString("TIMM_0217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出クランプ開→排出.持替位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0301 {
            get {
                return ResourceManager.GetString("TIMM_0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出.持替位置→排出クランプ閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0302 {
            get {
                return ResourceManager.GetString("TIMM_0302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出クランプ閉→搬送クランプ開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0303 {
            get {
                return ResourceManager.GetString("TIMM_0303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送クランプ開→排出.排出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0304 {
            get {
                return ResourceManager.GetString("TIMM_0304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排出.排出位置→排出クランプ開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0305 {
            get {
                return ResourceManager.GetString("TIMM_0305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバートップ: 搬送クランプ開→排出.排出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0306 {
            get {
                return ResourceManager.GetString("TIMM_0306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エアー吹き1.開始待ち時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0307 {
            get {
                return ResourceManager.GetString("TIMM_0307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エアー吹き1時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0308 {
            get {
                return ResourceManager.GetString("TIMM_0308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エアー吹き2.開始待ち時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0309 {
            get {
                return ResourceManager.GetString("TIMM_0309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エアー吹き2時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_030A {
            get {
                return ResourceManager.GetString("TIMM_030A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旋回.圧着ST→前後.圧着位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0401 {
            get {
                return ResourceManager.GetString("TIMM_0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旋回.圧着ST→圧着開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0402 {
            get {
                return ResourceManager.GetString("TIMM_0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着開始→No1沈み下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0403 {
            get {
                return ResourceManager.GetString("TIMM_0403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着開始→No1沈み上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0404 {
            get {
                return ResourceManager.GetString("TIMM_0404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1沈み上→前後.圧着検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0405 {
            get {
                return ResourceManager.GetString("TIMM_0405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着開始→PFMトリガ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0406 {
            get {
                return ResourceManager.GetString("TIMM_0406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.圧着ST→前後.圧着位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0507 {
            get {
                return ResourceManager.GetString("TIMM_0507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   搬送.圧着ST→圧着開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0508 {
            get {
                return ResourceManager.GetString("TIMM_0508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着開始→No2沈み下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0509 {
            get {
                return ResourceManager.GetString("TIMM_0509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着開始→No2沈み上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_050A {
            get {
                return ResourceManager.GetString("TIMM_050A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2沈み上→排出クランプ閉 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_050B {
            get {
                return ResourceManager.GetString("TIMM_050B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着開始→PFMトリガ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_050C {
            get {
                return ResourceManager.GetString("TIMM_050C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入開始位置→旋回.シール挿入ST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0601 {
            get {
                return ResourceManager.GetString("TIMM_0601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旋回.シール挿入ST→前後.シール挿入位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0602 {
            get {
                return ResourceManager.GetString("TIMM_0602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入位置→前後.シール挿入後退位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0603 {
            get {
                return ResourceManager.GetString("TIMM_0603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入後退位置→移動完了待ち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0604 {
            get {
                return ResourceManager.GetString("TIMM_0604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シールセット開始→前後.シール挿入開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0605 {
            get {
                return ResourceManager.GetString("TIMM_0605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入開始位置→旋回.ストリップST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0606 {
            get {
                return ResourceManager.GetString("TIMM_0606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入開始位置→旋回.シール挿入ST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0701 {
            get {
                return ResourceManager.GetString("TIMM_0701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旋回.シール挿入ST→前後.シール挿入位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0702 {
            get {
                return ResourceManager.GetString("TIMM_0702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入位置→前後.シール挿入後退位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0703 {
            get {
                return ResourceManager.GetString("TIMM_0703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入後退位置→移動完了待ち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0704 {
            get {
                return ResourceManager.GetString("TIMM_0704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シールセット開始→前後.シール挿入開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0705 {
            get {
                return ResourceManager.GetString("TIMM_0705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前後.シール挿入開始位置→旋回.ストリップST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMM_0706 {
            get {
                return ResourceManager.GetString("TIMM_0706", resourceCulture);
            }
        }
    }
}
